apiVersion: v1
kind: Service
metadata:
  name: inrad-app
  labels:
    app: inrad-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: inrad-app
    tier: frontend